# Generated by Django 2.0.6 on 2018-06-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='SignUp',
        ),
    ]
